export const queryKeys = {
  extrato: (mes: number, ano: number, apenasDivididas = false) =>
    ["extrato", mes, ano, apenasDivididas] as const,
  extratoPaginado: (
    mes: number,
    ano: number,
    dataInicial: string,
    dataFinal: string,
    pageNumber: number,
    pageSize: number,
    apenasDivididas = false,
    tipoTransacao = "todos",
    categoriaId: string | null = null,
    ordenarPor = "data",
    direcao = "desc",
  ) =>
    [
      "extrato-paginado",
      mes,
      ano,
      dataInicial,
      dataFinal,
      pageNumber,
      pageSize,
      apenasDivididas,
      tipoTransacao,
      categoriaId,
      ordenarPor,
      direcao,
    ] as const,
  faturas: (mes: number, ano: number) => ["faturas", mes, ano] as const,
  notificacoesNaoLidas: ["notificacoes", "nao-lidas"] as const,
  categorias: ["categorias"] as const,
  cartoes: ["cartoes"] as const,
  contas: ["contas"] as const,
  distribuicaoContas: ["distribuicao-contas"] as const,
  relatorios: (dataInicial: string, dataFinal: string) =>
    ["relatorios", dataInicial, dataFinal] as const,
  configuracoesNotificacao: ["notificacoes", "configuracoes"] as const,
};
