export const queryKeys = {
  extratoScope: ["extrato"] as const,
  extrato: (
    mes: number,
    ano: number,
    apenasDivididas = false,
    status = "todos",
  ) => ["extrato", mes, ano, apenasDivididas, status] as const,
  extratoPaginadoScope: ["extrato-paginado"] as const,
  extratoPaginado: (
    mes: number,
    ano: number,
    dataInicial: string,
    dataFinal: string,
    pageNumber: number,
    pageSize: number,
    apenasDivididas = false,
    tipoTransacao = "todos",
    categoriaIds: string[] = [],
    statuses: string[] = [],
    ordenarPor = "data",
    direcao = "desc",
  ) =>
    [
      "extrato-paginado",
      mes,
      ano,
      dataInicial,
      dataFinal,
      pageNumber,
      pageSize,
      apenasDivididas,
      tipoTransacao,
      normalizeKeyList(categoriaIds),
      normalizeKeyList(statuses),
      ordenarPor,
      direcao,
    ] as const,
  faturasScope: ["faturas"] as const,
  faturas: (mes: number, ano: number) => ["faturas", mes, ano] as const,
  notificacoesNaoLidas: ["notificacoes", "nao-lidas"] as const,
  categorias: ["categorias"] as const,
  cartoes: ["cartoes"] as const,
  contas: ["contas"] as const,
  distribuicaoContas: ["distribuicao-contas"] as const,
  dashboardScope: ["dashboard"] as const,
  dashboardInicio: (
    dataInicial = "",
    dataFinal = "",
    tipoTransacao = "todos",
    categoriaIds: string[] = [],
    statuses: string[] = [],
  ) =>
    [
      "dashboard",
      "inicio",
      dataInicial,
      dataFinal,
      tipoTransacao,
      normalizeKeyList(categoriaIds),
      normalizeKeyList(statuses),
    ] as const,
  relatoriosScope: ["relatorios"] as const,
  relatorios: (
    dataInicial: string,
    dataFinal: string,
    contaBancariaId = "",
    cartaoCreditoId = "",
    categoriaIds: string[] = [],
    tipoTransacao = "todos",
    status = "todos",
    somenteRecorrentes = false,
    somenteParceladas = false,
    secoes: string[] = [],
  ) =>
    [
      "relatorios",
      normalizeKeyList(secoes),
      dataInicial,
      dataFinal,
      contaBancariaId,
      cartaoCreditoId,
      normalizeKeyList(categoriaIds),
      tipoTransacao,
      status,
      somenteRecorrentes,
      somenteParceladas,
    ] as const,
  configuracoesNotificacao: ["notificacoes", "configuracoes"] as const,
};

function normalizeKeyList(values: string[]) {
  return [...new Set(values.filter(Boolean))].sort().join(",");
}
