// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SistemaFinanceiro.Api.Data;

#nullable disable

namespace SistemaFinanceiro.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615233000_AddStatusPagamentoFaturaCartao")]
    partial class AddStatusPagamentoFaturaCartao
    {
    }
}
