// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaFinanceiro.Api.Data;

#nullable disable

namespace SistemaFinanceiro.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603085055_AddCarneCrediarioCompraParcelada")]
    partial class AddCarneCrediarioCompraParcelada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaFinanceiro.Api.Models.CartaoCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApelidoCartao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("apelido_cartao");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("banco");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_vencimento");

                    b.Property<decimal>("LimiteTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("limite_total");

                    b.Property<int>("MelhorDiaCompra")
                        .HasColumnType("integer")
                        .HasColumnName("melhor_dia_compra");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "ApelidoCartao");

                    b.ToTable("cartoes_credito", (string)null);
                });

            modelBuilder.Entity("SistemaFinanceiro.Api.Models.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorHexa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("cor_hexa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Nome")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d2cc7a6-e150-433d-bc47-97b401078f86"),
                            CorHexa = "#2563EB",
                            Nome = "🏠 Casa"
                        },
                        new
                        {
                            Id = new Guid("6b7df4e6-6937-4c07-9e6f-7d19efa15177"),
                            CorHexa = "#DC2626",
                            Nome = "🚗 Carro"
                        },
                        new
                        {
                            Id = new Guid("86299a6c-6d3a-49d2-b862-9340673d0425"),
                            CorHexa = "#7C3AED",
                            Nome = "📚 Educação"
                        },
                        new
                        {
                            Id = new Guid("f3e02a07-08e6-47a0-824d-3acc930c537e"),
                            CorHexa = "#DB2777",
                            Nome = "🎮 Lazer"
                        },
                        new
                        {
                            Id = new Guid("06fa9f77-5ac4-42d7-aa5a-4f98a38fe692"),
                            CorHexa = "#059669",
                            Nome = "📈 Investimento"
                        },
                        new
                        {
                            Id = new Guid("c8763c27-954e-439c-9b22-7ff05356c12b"),
                            CorHexa = "#EA580C",
                            Nome = "🍽️ Alimentação"
                        });
                });

            modelBuilder.Entity("SistemaFinanceiro.Api.Models.CompraParcelada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CartaoCreditoId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cartao_credito");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_categoria");

                    b.Property<DateOnly>("DataCompra")
                        .HasColumnType("date")
                        .HasColumnName("data_compra");

                    b.Property<DateOnly?>("DataPrimeiroVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_primeiro_vencimento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("descricao");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("CartaoCredito")
                        .HasColumnName("forma_pagamento");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_parcelas");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("CartaoCreditoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("compras_parceladas", (string)null);
                });

            modelBuilder.Entity("SistemaFinanceiro.Api.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SistemaFinanceiro.Api.Models.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CartaoCreditoId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cartao_credito");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_categoria");

                    b.Property<int>("CodigoExibicao")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_exibicao");

                    b.Property<Guid?>("CompraParceladaId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_compra_parcelada");

                    b.Property<DateOnly>("DataOcorrencia")
                        .HasColumnType("date")
                        .HasColumnName("data_ocorrencia");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("descricao");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("forma_pagamento");

                    b.Property<bool>("IsFixa")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fixa");

                    b.Property<int?>("NumeroParcelaQuitada")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcela_quitada");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("CartaoCreditoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CompraParceladaId");

                    b.HasIndex("UsuarioId", "CodigoExibicao")
                        .IsUnique();

                    b.ToTable("transacoes", (string)null);
                });

            modelBuilder.Entity("SistemaFinanceiro.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("SistemaFinanceiro.Api.Models.CartaoCredito", b =>
                {
                    b.HasOne("SistemaFinanceiro.Api.Models.Usuario", "Usuario")
                        .WithMany("CartoesCredito")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaFinanceiro.Api.Models.Categoria", b =>
                {
                    b.HasOne("SistemaFinanceiro.Api.Models.Usuario", "Usuario")
                        .WithMany("Categorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaFinanceiro.Api.Models.CompraParcelada", b =>
                {
                    b.HasOne("SistemaFinanceiro.Api.Models.CartaoCredito", "CartaoCredito")
                        .WithMany("ComprasParceladas")
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaFinanceiro.Api.Models.Categoria", "Categoria")
                        .WithMany("ComprasParceladas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaFinanceiro.Api.Models.Usuario", "Usuario")
                        .WithMany("ComprasParceladas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartaoCredito");

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaFinanceiro.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("SistemaFinanceiro.Api.Models.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaFinanceiro.Api.Models.Transacao", b =>
                {
                    b.HasOne("SistemaFinanceiro.Api.Models.CartaoCredito", "CartaoCredito")
                        .WithMany("Transacoes")
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaFinanceiro.Api.Models.Categoria", "Categoria")
                        .WithMany("Transacoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaFinanceiro.Api.Models.CompraParcelada", "CompraParcelada")
                        .WithMany("TransacoesQuitacao")
                        .HasForeignKey("CompraParceladaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaFinanceiro.Api.Models.Usuario", "Usuario")
                        .WithMany("Transacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartaoCredito");

                    b.Navigation("Categoria");

                    b.Navigation("CompraParcelada");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaFinanceiro.Api.Models.CartaoCredito", b =>
                {
                    b.Navigation("ComprasParceladas");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("SistemaFinanceiro.Api.Models.Categoria", b =>
                {
                    b.Navigation("ComprasParceladas");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("SistemaFinanceiro.Api.Models.CompraParcelada", b =>
                {
                    b.Navigation("TransacoesQuitacao");
                });

            modelBuilder.Entity("SistemaFinanceiro.Api.Models.Usuario", b =>
                {
                    b.Navigation("CartoesCredito");

                    b.Navigation("Categorias");

                    b.Navigation("ComprasParceladas");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
